# Generated by Django 5.1.2 on 2024-10-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('birthdate', models.DateField(verbose_name='Birthdate')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created date')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
