# Generated by Django 5.1.2 on 2024-11-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(choices=[('Earring', 'Earring'), ('Necklace', 'Necklace'), ('Ring', 'Ring'), ('Bracelet', 'Bracelet'), ('Pendant', 'Pendant'), ('Choker', 'Choker')], null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='deffered_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Deferred price'),
        ),
    ]
